### ISSUE TITLE
Installation tutorial is broken.

### ISSUE THREAD

**Issue by AlejandroUPC** [unagex/metabase-operator#1]
Hi, first of all thanks for setting this up, it seems really cool.

When following the README.md tutorial and running the commands on an EKS cluster:

```sh
helm repo add metabase-operator-charts https://unagex.github.io/metabase-operator
helm repo update
helm install metabase-operator metabase-operator-charts/metabase-operator
kubectl apply -f https://raw.githubusercontent.com/unagex/metabase-operator/main/config/samples/v1_metabase.yaml
```

The installation will fail 

```sh
error: error parsing https://github.com/unagex/metabase-operator/blob/main/config/samples/v1_metabase.yaml: error converting YAML to JSON: yaml: line 212: mapping values are not allowed in this context
```

Probably because some of the commented values, uncommenting the lines and using the following file will work:

```yaml
apiVersion: unagex.com/v1
kind: Metabase
metadata:
  name: metabase-sample
spec:
  metabase:
    image: "metabase/metabase:latest"
    imagePullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: 1
        memory: 2Gi
  db:
    image: "postgres:latest"
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    resources:
      requests:
        cpu: 1
        memory: 2Gi
    volume:
      # storageClassName: standard
      size: 10Gi
```

I am not very familiar with operators and go, so I am bit afraid to commit an MR, although the problem seems quite obvious and its just a YAML issue.
