### ISSUE TITLE
[FEAT] Possibility to add env vars to metabase.

### ISSUE THREAD

**Issue by Vinaum8** [unagex/metabase-operator#3]
Currently, when running:

`kubectl explain metabase.spec.metabase`

there is no option to define environment variables for the Metabase pod. This limitation makes it difficult to configure Metabase dynamically, as many settings rely on environment variables (e.g., database credentials, authentication settings, and performance tuning parameters).

### Proposed Solution

It would be beneficial to introduce support for defining environment variables directly within metabase.spec.metabase. This could follow a similar structure to other Kubernetes resources, where users can specify env and envFrom fields.

Example:
```
apiVersion: metabase.example.com/v1
kind: Metabase
metadata:
  name: my-metabase
spec:
  metabase:
    env:
      - name: MB_DB_TYPE
        value: "postgres"
      - name: MB_DB_HOST
        value: "my-postgres-db"
    envFrom:
      - secretRef:
          name: metabase-secrets
```

By implementing this, users would gain greater flexibility in configuring Metabase instances while following Kubernetes best practices.

### Benefits
- Enables dynamic configuration through environment variables.
- Simplifies integration with external systems (e.g., databases, authentication providers).
- Aligns with standard Kubernetes conventions for defining pod environment variables.

Would love to hear your thoughts on this feature! Let me know if I can provide further details. 🚀
